In [1]:
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 22 14:47:20 2019

Author:Mwangi
Purpose: Lists ,Sets and Dictionaries in Python
- A list is a container which we used to store multiple data
- Set is also another python collection data type. Set’s can’t have duplicates.
- Dictionary is also a python collection data type. These are unordered, changeable 
- and indexed. In python dictionaries are written using curly brackets. “{}”. Dictionaries have keys and values.
"""
print("---------Lists----------\n")

Lists_Participants = [10,21,23,36,25,14,78,96,85,74,41,52,63,30,20,]
print (Lists_Participants)
print(Lists_Participants[2])
print(Lists_Participants[7])
print(Lists_Participants[5])
print(Lists_Participants[9])

print("---------Sets----------\n")

names = {'Ben','Penalty', 'Curtis', 'Yidah','Curtis', 'Everton', 'Yidah'}
for i in names:
    print(i)
    

print("---------Dictionaries----------\n")

names = {'Ben - ':'Male ','Penalty - ':'Sports', 'Curtis - ':'Male', 'Yidah - ':'Player','Curtis - ':'Boy','Everton - ':'Club', 'Yidah - ':'Man'}
for i, j  in names.items():
    print(i+j)




---------Lists----------

[10, 21, 23, 36, 25, 14, 78, 96, 85, 74, 41, 52, 63, 30, 20]
23
96
14
74
---------Sets----------

Curtis
Penalty
Ben
Yidah
Everton
---------Dictionaries----------

Ben - Male 
Penalty - Sports
Curtis - Boy
Yidah - Man
Everton - Club


In [2]:
# tuples are immutable

import numpy as np

tupl = ('wangwang', np.arange(0,3,0.2), 2.5)
tupl

('wangwang',
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8]),
 2.5)

In [4]:
tupl = ['wangwang']
tupl.append('Wangwang-ngo')
tupl

['wangwang', 'Wangwang-ngo']

In [8]:
'''
a[start:end]
# items start through end-1 a[start:] 
# items start through the rest of the array a[:end] 
# items from the beginning through end-1 a[:] 
# a copy of the whole array

'''
tupl[-1]
tupl[-2:]
tupl[:-2]
tupl[-1:3]

['Wangwang-ngo']

Vectors and Arrays


In [9]:
import numpy as np

np.zeros(5)


array([0., 0., 0., 0., 0.])

np.zeros()

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

np.ones()

np.arange()

In [12]:
np.arange(3)

array([0, 1, 2])

np.linspace

In [13]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

np.array()

In [15]:
np.array([[1,2], [4,9]])

array([[1, 2],
       [4, 9]])