<a href="https://colab.research.google.com/github/mngugi/Python_Collections-/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matrA = np.random.randn(3,3)
print(matrA)
print('---------------')

print('A string Matrix')
matrB = np.array([['Ford', 'Benz'], ['Toyota', 'Honda']])
matrB

[[ 0.1668064  -1.0772786  -2.81670734]
 [-0.98746107 -0.25694347  1.38842923]
 [-0.03014958 -0.79706134  0.62701345]]
---------------
A string Matrix


array([['Ford', 'Benz'],
       ['Toyota', 'Honda']], dtype='<U6')