<a href="https://colab.research.google.com/github/mngugi/-Bash-/blob/main/Recap_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

list1 = [1,2,3,4,5]
list2 = [11,12,13,14,15]

# convert the list into an array
j = np.array(list1)
i = np.array(list2)
# add
kadd = j+i
print(kadd)

#subtract

ksubtract = j - i
print(ksubtract)

#multiplication
kmultiple = j * i
print(kmultiple)

#dotproduct - scalar value
kdot = j @ i
print(kdot)

[12 14 16 18 20]
[-10 -10 -10 -10 -10]
[11 24 39 56 75]
205
