In [1]:
print("jupyter configured")

jupyter configured


In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-06-11 21:23:01.338763: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-11 21:23:01.382437: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-11 21:23:01.383303: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-11 21:23:02.319273: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


TensorFlow version: 2.12.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 9s 1us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.20263644, -0.16678214,  0.45415446, -0.22839957, -0.15624821,
         0.49765623,  1.1267651 ,  0.21667835, -0.1124837 , -0.37197906]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()


array([[0.09528355, 0.0658539 , 0.12253238, 0.06191863, 0.06655126,
        0.1279804 , 0.24008329, 0.09663096, 0.06952852, 0.05363714]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.0558782

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0878 - accuracy: 0.9726
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0780 - accuracy: 0.9751
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0660 - accuracy: 0.9795
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0591 - accuracy: 0.9810
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0538 - accuracy: 0.9825


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0941 - accuracy: 0.9718 - 445ms/epoch - 1ms/step


[0.09414096921682358, 0.9718000292778015]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.15802556e-10, 2.73456761e-11, 2.85910374e-07, 7.56735744e-06,
        2.04488593e-13, 8.02414191e-10, 2.23383817e-16, 9.99991775e-01,
        4.54013929e-08, 4.44517809e-07],
       [4.21061103e-10, 1.51581582e-06, 9.99998450e-01, 5.43531720e-10,
        7.49536454e-22, 2.52223575e-09, 9.29113817e-12, 7.47496402e-18,
        1.33230760e-09, 1.76140770e-18],
       [3.21139804e-09, 9.99924779e-01, 1.88465856e-05, 5.78743425e-07,
        2.41453995e-06, 2.35561970e-06, 5.81812571e-07, 4.81116185e-05,
        2.39225915e-06, 3.72029518e-09],
       [9.99978662e-01, 4.91772352e-11, 1.16078281e-05, 1.33354554e-08,
        3.72752957e-08, 1.29741267e-07, 9.09695427e-06, 1.16158546e-07,
        3.62895602e-09, 3.95976002e-07],
       [1.16442106e-06, 9.06731704e-11, 1.07202982e-06, 2.06421991e-09,
        9.99441922e-01, 1.03880700e-08, 3.77211421e-07, 6.69155907e-06,
        1.31966132e-07, 5.48686367e-04]], dtype=float32)>

In [16]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0
