In [1]:
import numpy as np
from sklearn.decomposition import PCA       # optional, pip install scikit-learn
from sklearn.metrics.pairwise import cosine_similarity

# --- simple toy features for 5 versions (you can expand) ---
versions = ["Win3.1","Win95","WinXP","Win7","Win11"]
# each row = [StartMenu, TouchSupport, FlatIcons, Transparency] values 0..1
V = np.array([
  [0.9, 0.0, 0.1, 0.0],  # Win3.1
  [0.8, 0.0, 0.2, 0.0],  # Win95
  [0.6, 0.1, 0.5, 0.1],  # WinXP
  [0.4, 0.4, 0.7, 0.6],  # Win7
  [0.2, 0.9, 1.0, 0.8],  # Win11
])

# normalize
Vn = V / (np.linalg.norm(V, axis=1, keepdims=True) + 1e-9)

# cosine similarity matrix
S = cosine_similarity(Vn)

# optional: PCA to K dims
K = 2
pca = PCA(n_components=K)
emb = pca.fit_transform(V)   # shape (n_versions, K)

# simple iterative evolution from first version
gamma = 0.3
base_x = 1    # base_x+1 iterations
v = V[0].copy()
for i in range(base_x + 1):
    # innovation = small step toward next version (or toward mean)
    if i+1 < len(V):
        innovation = (V[i+1] - v) * 0.2
    else:
        innovation = (V.mean(axis=0) - v) * 0.05
    v = (1-gamma)*v + gamma*(v + innovation)

print("Versions:", versions)
print("Cosine similarity matrix:\n", np.round(S,3))
print("2D embedding (PCA):\n", np.round(emb,3))
print("Iterated vector after base_x+1 steps:\n", np.round(v,3))


Versions: ['Win3.1', 'Win95', 'WinXP', 'Win7', 'Win11']
Cosine similarity matrix:
 [[1.    0.991 0.821 0.439 0.196]
 [0.991 1.    0.886 0.516 0.277]
 [0.821 0.886 1.    0.804 0.631]
 [0.439 0.516 0.804 1.    0.949]
 [0.196 0.277 0.631 0.949 1.   ]]
2D embedding (PCA):
 [[-0.646  0.117]
 [-0.553  0.014]
 [-0.21  -0.161]
 [ 0.399 -0.032]
 [ 1.01   0.062]]
Iterated vector after base_x+1 steps:
 [0.876 0.006 0.13  0.006]
